/**
 * Created by strawmanbobi
 * 2017-03-27
 */

let LS_KEY_ID = 'user_name';
let LS_KEY_TOKEN = 'token';

let CATEGORY_AC = 1;
let CATEGORY_TV = 2;
let CATEGORY_STB = 3;
let CATEGORY_NW = 4;
let CATEGORY_IPTV = 5;
let CATEGORY_DVD = 6;
let CATEGORY_FAN = 7;
let CATEGORY_PROJECTOR = 8;
let CATEGORY_STEREO = 9;
let CATEGORY_LIGHT_BULB = 10;
let CATEGORY_BSTB = 11;
let CATEGORY_CLEANING_ROBOT = 12;
let CATEGORY_AIR_CLEANER = 13;
let CATEGORY_DYSON = 14;

let TRANSFER_STATE_NONE = 0;
let TRANSFER_STATE_BIN_FETCHED = 1;
let TRANSFER_STATE_BIN_ON_GOING = 2;
let TRANSFER_STATE_BIN_DONE = 3;